---
#wso2_mb Queries
- name: Excuting Query 1 in wso2_mb
  mysql_db:
    state: import
    name: wso2_mb
    target: /opt/MB/wso2mb-3.2.0/dbscripts/mb-store/mysql-mb.sql
#userdb queries
- name: Excuting Query 1 in userdb
  mysql_db:
    state: import
    name: userdb
    target: /opt/MB/wso2mb-3.2.0/dbscripts/mysql5.7.sql

#REGISTRY_DB queries
- name: Excuting Query 1 in regdb
  mysql_db:
    state: import
    name: regdb
    target: /opt/MB/wso2mb-3.2.0/dbscripts/mysql5.7.sql

